vich_uploader:
    db_driver: orm

    mappings:
       images:
           uri_prefix: /images/all
           upload_destination: '%kernel.project_dir%/public/images/all'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
