vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images/all
            upload_destination: '%kernel.project_dir%/public/images/all'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        blog_image:
            uri_prefix: /images/blog/obrazky
            upload_destination: '%kernel.project_dir%/public/images/blog/obrazky'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        blog_image_gallery:
            uri_prefix: /images/blog/galerie
            upload_destination: '%kernel.project_dir%/public/images/blog/galerie'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
